Issue #225, solved ! Numbers that starts with . should be allowed
ferraridamiano/ConverterNOW pull request #234
Opened 2023-07-16 22:07 UTC by HarshMakwana27

Issue fixed by changes in onChanged and validator.

2023-07-17 18:26 UTC, ferraridamiano requested changes
Looks good! Just leaved few comments

2023-07-17 18:26 UTC, ferraridamiano commented on android/gradle/wrapper/gradle-wrapper.properties
Could you please revert the changes on this file? Gradle upgrade should not be included in this PR

2023-07-17 18:26 UTC, ferraridamiano commented on pubspec.yaml
Could you please revert the changes on this file?

If you do as you suggest we ends up including all the svg files + their compiled version while we would like to keep just the optimized one

2023-07-17 19:14 UTC, HarshMakwana27 commented on pubspec.yaml
fixed

2023-07-18 17:33 UTC, ferraridamiano approved these changes

2023-07-18 17:37 UTC, merged

2023-07-18 17:38 UTC, ferraridamiano commented
Thank you @HarshMakwana27
There are a lot of issues like this tha could be fixed if you want :)