Updated polish translation
ferraridamiano/ConverterNOW pull request #281
Opened 2024-03-05 22:40 UTC by rehork

2024-03-09 15:26 UTC, ferraridamiano requested changes
Could you remove the extra closing curly brackets?

2024-03-10 09:39 UTC, rehork reviewed
I hope it's fine now

2024-03-10 09:42 UTC, ferraridamiano approved these changes

2024-03-10 09:43 UTC, merged

2024-03-10 09:43 UTC, ferraridamiano commented
Thank you!