Greek translation
ferraridamiano/ConverterNOW pull request #306
Opened 2024-10-25 16:44 UTC by makishart

Hello I would like to contribute with a Greek translation

2024-10-25 18:23 UTC, ferraridamiano requested changes

2024-10-25 18:23 UTC, ferraridamiano commented on packages/translations/lib/l10n/app_gr.arb
> +  "@@locale": "gr",
Same here

2024-10-25 18:23 UTC, ferraridamiano commented on lib/models/settings.dart
> +  const Locale('gr'): 'Ελληνικά',
I think that the CI failed because the language code for Greek is el and not gr

2024-10-25 18:24 UTC, makishart commented on lib/models/settings.dart
> +  const Locale('gr'): 'Ελληνικά',
Yes, sorry for that

2024-10-25 18:24 UTC, makishart commented on lib/models/settings.dart
> +  const Locale('gr'): 'Ελληνικά',
Shall I make a new pull request?

2024-10-25 18:33 UTC, makishart commented on lib/models/settings.dart
> +  const Locale('gr'): 'Ελληνικά',
Ok, I changed it at el

2024-10-26 13:00 UTC, merged

2024-10-26 13:00 UTC, ferraridamiano commented
Thank you!